
import { AiProviderPort } from '../providers/AiProviderPort';
import { AnalysisResult, DataQualityResult } from '../types';

export class DataQualityAgent {
    constructor(private readonly aiProvider: AiProviderPort) {}

    async run(analysisSoFar: Partial<AnalysisResult['finalResult']>): Promise<DataQualityResult> {
        const prompt = `
        As a Data Quality Agent, your job is to review the AI-generated content for a product.
        Assess its quality, consistency, and adherence to the initial request.
        
        Here is the data generated by other agents:
        - SEO Keywords: ${analysisSoFar.seo?.keywords.join(', ')}
        - Copywriting Snippet: ${analysisSoFar.copywriting?.htmlReview.substring(0, 100)}...
        - Image Prompts: ${analysisSoFar.visuals?.imagePrompts.join('; ')}

        Provide a final quality score from 0.0 to 1.0 and brief feedback.
        
        Return a JSON object with 'overallScore' (a number) and 'feedback' (a string).
        
        Example response format:
        {
          "overallScore": 0.92,
          "feedback": "The generated content is high-quality and internally consistent. The SEO keywords align well with the product copy."
        }
        `;

        const response = await this.aiProvider.call(prompt);
         if (!response.success || !response.content) {
            console.error("DataQualityAgent failed:", response.error);
            return { overallScore: 0, feedback: "Failed to perform quality check." };
        }
        try {
            return JSON.parse(response.content) as DataQualityResult;
        } catch (e) {
            console.error("DataQualityAgent failed to parse JSON:", e);
            return { overallScore: 0, feedback: "Failed to parse quality check response." };
        }
    }
}
